// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://gen` | (string & {});
};

/**
 * A range annotation spanning a wall-clock window within a run (rather than a single target event).
 */
export type AnnotateRangeRequest = {
    /**
     * The run (session) the annotation belongs to.
     */
    runId?: string;
    /**
     * The registered annotation-schema name the payload validates against (the event `name`).
     */
    schemaName?: string;
    /**
     * Inclusive start of the annotated window, in wall-clock nanoseconds.
     */
    rangeStartNs?: string;
    /**
     * Inclusive end of the annotated window, in wall-clock nanoseconds.
     */
    rangeEndNs?: string;
    /**
     * The annotation payload as a JSON object string; validated against `schema_name`'s registered
     * JSON Schema at ingest. Reserved `hiloop.annotation.*` keys are platform-owned and excluded.
     */
    payloadJson?: string;
    /**
     * The fork-node path the annotation is anchored at. Empty means the run root.
     */
    forkPath?: string;
    /**
     * Who produced the annotation (e.g. "human", "llm"); stamped as the reserved annotator-kind key.
     */
    annotatorKind?: string;
};

/**
 * A point annotation about a single target event.
 */
export type AnnotateRequest = {
    /**
     * The run (session) the annotation belongs to.
     */
    runId?: string;
    /**
     * The registered annotation-schema name the payload validates against (the event `name`).
     */
    schemaName?: string;
    /**
     * The `event_id` of the single event this annotation is about.
     */
    targetEventId?: string;
    /**
     * The annotation payload as a JSON object string; validated against `schema_name`'s registered
     * JSON Schema at ingest. Reserved `hiloop.annotation.*` keys are platform-owned and excluded.
     */
    payloadJson?: string;
    /**
     * The fork-node path the annotation is anchored at. Empty means the run root.
     */
    forkPath?: string;
    /**
     * Who produced the annotation (e.g. "human", "llm"); stamped as the reserved annotator-kind key.
     */
    annotatorKind?: string;
};

export type AnnotateResponse = {
    /**
     * The minted, stable `event_id` of the annotation event (the dedup/lookup key).
     */
    eventId?: string;
};

/**
 * One registered annotation-schema config: a single immutable, versioned row of the registry.
 */
export type AnnotationSchema = {
    /**
     * The config id.
     */
    id?: string;
    /**
     * The tenant the config belongs to (derived from the caller's scope, echoed for convenience).
     */
    tenantId?: string;
    /**
     * The schema name — unique per tenant across versions (the registered name an annotation names).
     */
    name?: string;
    /**
     * The monotonic version within (tenant, name). The first registration is 1.
     */
    version?: string;
    /**
     * An optional human-readable description.
     */
    description?: string;
    /**
     * The JSON Schema document (draft 2020-12) as a JSON string.
     */
    jsonSchema?: string;
    /**
     * When the config was archived (RFC 3339), or empty if it is still live.
     */
    archivedAt?: string;
    /**
     * When the config version was created (RFC 3339).
     */
    createdAt?: string;
};

export type ArchiveAnnotationSchemaRequest = {
    /**
     * The schema name to archive.
     */
    name?: string;
    /**
     * The specific version to archive. 0 (or omitted) means the latest live version.
     */
    version?: string;
};

export type ArchiveAnnotationSchemaResponse = {
    /**
     * The archived config version.
     */
    schema?: AnnotationSchema;
};

export type Artifact = {
    id?: string;
    tenantId?: string;
    kind?: string;
    mediaType?: string;
    sizeBytes?: string;
    digestAlgorithm?: string;
    digest?: string;
};

/**
 * A typed scalar attribute value (mirrors the Event v1 narrow value model).
 */
export type AttributeValue = {
    stringValue?: string;
    intValue?: string;
    doubleValue?: number;
    boolValue?: boolean;
};

export type BranchDiffRequest = {
    spec?: BranchDiffSpec;
};

export type BranchDiffResponse = {
    /**
     * Events present under `path_a` but not under `path_b`, projected to the diff key columns.
     */
    rows?: Array<Row>;
};

/**
 * A branch-diff (Q3): the events under subtree `path_a` that are absent under subtree `path_b`,
 * within one run. This is the differentiated tree-native query — two anchored `fork_path` prefix
 * scans, set-differenced on a semantic key (signal, name, attributes). The tenant is taken from
 * request identity, never from this body.
 */
export type BranchDiffSpec = {
    /**
     * The run (session) both branches belong to. Required.
     */
    runId?: string;
    /**
     * The subtree whose unique events to return (the "A" branch). Required; anchored by `fork_path`
     * prefix (the node plus its descendants).
     */
    pathA?: string;
    /**
     * The subtree to subtract (the "B" branch). Required.
     */
    pathB?: string;
    /**
     * Optional signal to restrict the diff to (e.g. "llm"); empty means all signals.
     */
    signal?: string;
};

export type BuildArtifactImage = {
    artifactRef?: string;
};

export type Capability = {
    key?: string;
    support?: string;
    maturity?: string;
};

export type CapabilityRequirement = {
    key?: string;
    minimumSupport?: string;
    minimumMaturity?: string;
};

export type CaptureSpec = {
    /**
     * Compatibility capture toggle for existing clients. Omit this field, or omit the parent
     * `capture` field, to use the default-enabled policy.
     */
    enabled?: boolean;
    /**
     * REST-safe capture policy. Use CAPTURE_POLICY_DISABLED to run the sandbox with no capture
     * instrumentation; omitted or CAPTURE_POLICY_UNSPECIFIED defaults to enabled.
     */
    policy?: 'CAPTURE_POLICY_UNSPECIFIED' | 'CAPTURE_POLICY_ENABLED' | 'CAPTURE_POLICY_DISABLED';
};

export type CommandSpec = {
    program?: string;
    args?: Array<string>;
    env?: {
        [key: string]: string;
    };
    workingDir?: string;
    /**
     * Zero uses the server default command timeout.
     */
    timeoutSecs?: string;
};

export type CreateProjectRequest = {
    /**
     * The project slug — unique within the caller's tenant.
     */
    slug?: string;
    /**
     * The human-readable project name.
     */
    name?: string;
};

export type CreateProjectResponse = {
    /**
     * The created project.
     */
    project?: Project;
};

export type CreateSandboxRequest = {
    projectId?: string;
    name?: string;
    image?: SandboxImage;
    resources?: ResourceSpec;
    requestedCapabilities?: Array<CapabilityRequirement>;
    labels?: {
        [key: string]: string;
    };
    capture?: CaptureSpec;
    /**
     * Outbound network policy. Omitted leaves egress unbounded (default-allow).
     */
    egress?: EgressPolicy;
    /**
     * Secret bindings injected into matching outbound requests. Empty injects nothing.
     */
    secrets?: Array<SecretBinding>;
};

export type CreateSandboxResponse = {
    sandbox?: Sandbox;
    operation?: Operation;
};

export type CreateSandboxSecretRequest = {
    /**
     * The secret name — unique within the caller's tenant.
     */
    name?: string;
    /**
     * The credential kind.
     */
    kind?: 'SECRET_KIND_UNSPECIFIED' | 'SECRET_KIND_API_KEY' | 'SECRET_KIND_BEARER' | 'SECRET_KIND_BASIC' | 'SECRET_KIND_CUSTOM';
    /**
     * The secret value. WRITE-ONLY: stored encrypted and never returned by this API again; the proxy
     * resolves it at request time.
     */
    value?: string;
    /**
     * The outbound host to inject the value into (optional).
     */
    destHost?: string;
    /**
     * The header to inject the value as (optional; defaults by kind).
     */
    destHeader?: string;
    /**
     * The auth scheme prefix (optional; e.g. `Bearer`).
     */
    scheme?: string;
};

export type CreateSandboxSecretResponse = {
    /**
     * The created secret's metadata. The value is NOT echoed back.
     */
    secret?: SandboxSecret;
};

export type CreateSnapshotRequest = {
    sandboxId?: string;
    contents?: string;
    allowFallback?: boolean;
    retentionClass?: string;
    ttlSecs?: string;
    legalHold?: boolean;
    /**
     * Optional path to a stable file whose bytes should be recorded at capture time and verified after
     * every restore of this snapshot. Callers should quiesce writes to this path before requesting the
     * snapshot.
     */
    verificationProbePath?: string;
};

export type CreateSnapshotResponse = {
    operation?: Operation;
};

/**
 * A structured data view: a named, versioned spec that compiles 1:1 to a safe query.
 */
export type DataView = {
    /**
     * The view name, unique within a tenant among non-deleted views.
     */
    name?: string;
    /**
     * A human description, surfaced in the console switcher.
     */
    description?: string;
    /**
     * The structured spec as opaque JSON — the engine's tagged `DataViewSpec` shape (a Query or Rollup
     * view: scope + calculations + breakdowns + filters + orders + limit + opaque render config). Carried
     * as a Struct so the spec schema lives in ONE place (the engine's serde types); the service never
     * re-models it. Re-validated against the current column allowlist on store and on every run, so a
     * view referencing a dropped column fails closed with INVALID_ARGUMENT rather than serving a stale
     * result.
     */
    spec?: {
        [key: string]: unknown;
    };
    /**
     * Monotonic per-edit version; the store bumps it on each upsert.
     */
    specVersion?: string;
    /**
     * A seeded starter view (read-only; clone-on-edit per tenant). Customer-authored views are false.
     */
    isBuiltin?: boolean;
};

export type DeleteDataViewResponse = {
    [key: string]: unknown;
};

export type DeleteSandboxResponse = {
    operation?: Operation;
};

export type DeleteSavedViewResponse = {
    [key: string]: unknown;
};

export type DeleteSnapshotResponse = {
    snapshot?: Snapshot;
    operation?: Operation;
};

/**
 * Provider-neutral outbound network policy for a sandbox. Omitted or EGRESS_MODE_UNSPECIFIED leaves
 * outbound traffic unbounded (the default-allow behavior). Enforced at the strongest layer the
 * runtime supports.
 */
export type EgressPolicy = {
    /**
     * Whether the lists below are an allowlist (deny mode) or a denylist (allow mode).
     */
    mode?: 'EGRESS_MODE_UNSPECIFIED' | 'EGRESS_MODE_ALLOW' | 'EGRESS_MODE_DENY';
    /**
     * Suffix-matched destination domains the policy applies to.
     */
    domains?: Array<string>;
    /**
     * Destination IP ranges, in CIDR notation, the policy applies to.
     */
    cidrs?: Array<string>;
};

/**
 * Final disposition of an interactive execution.
 */
export type ExecExit = {
    /**
     * Process exit code. Meaningful only when the process exited normally.
     */
    exitCode?: string;
    /**
     * Terminating signal number, or 0 when the process exited normally.
     */
    signal?: number;
};

/**
 * One framed event in an execution's combined output stream.
 */
export type ExecOutputEvent = {
    /**
     * A chunk of standard output bytes.
     */
    stdoutChunk?: string;
    /**
     * A chunk of standard error bytes.
     */
    stderrChunk?: string;
    /**
     * The terminal exit event. No further events follow it.
     */
    exit?: ExecExit;
};

export type ExecuteSandboxRequest = {
    sandboxId?: string;
    command?: CommandSpec;
    stdin?: string;
};

export type ExecuteSandboxResponse = {
    execution?: Execution;
    operation?: Operation;
};

export type Execution = {
    id?: string;
    tenantId?: string;
    sandboxId?: string;
    state?: string;
    exitCode?: string;
    stdoutArtifactId?: string;
    stderrArtifactId?: string;
};

export type FileFromArtifactRequest = {
    sandboxId?: string;
    artifactId?: string;
    path?: string;
};

export type FileFromArtifactResponse = {
    operation?: Operation;
};

export type FileToArtifactRequest = {
    sandboxId?: string;
    path?: string;
    mediaType?: string;
};

export type FileToArtifactResponse = {
    operation?: Operation;
};

export type Fork = {
    id?: string;
    tenantId?: string;
    sourceSandboxId?: string;
    sourceSnapshotId?: string;
    childSandboxId?: string;
    forkNodeId?: string;
    implementation?: string;
    effectiveSemanticsJson?: string;
    intermediateSnapshotId?: string;
    operationId?: string;
};

/**
 * A fork-tree node: one position in a run's fork lineage, shared with telemetry.
 */
export type ForkNode = {
    /**
     * The fork node id (a client-supplied ULID, shared with telemetry).
     */
    id?: string;
    /**
     * The run this fork node belongs to.
     */
    runId?: string;
    /**
     * The gap-free fork path as a dotted ltree label (e.g. "1.2.1").
     */
    forkPath?: string;
    /**
     * The parent fork node id, empty for a root node.
     */
    parentForkNodeId?: string;
    /**
     * The fork node status: active or archived.
     */
    status?: string;
    /**
     * When the fork node was created (RFC 3339).
     */
    createdAt?: string;
};

export type ForkSandboxRequest = {
    sourceSandboxId?: string;
    parentForkNodeId?: string;
    childForkNodeId?: string;
    projectId?: string;
    name?: string;
    image?: SandboxImage;
    resources?: ResourceSpec;
    requestedCapabilities?: Array<CapabilityRequirement>;
    labels?: {
        [key: string]: string;
    };
    continuity?: string;
    allowFallback?: boolean;
    /**
     * Activity-capture policy for the child sandbox. Enabled by default; set
     * policy=CAPTURE_POLICY_DISABLED to fork onto an image without the capture toolchain.
     */
    capture?: CaptureSpec;
    /**
     * Outbound network policy for the child sandbox. Omitted leaves egress unbounded.
     */
    egress?: EgressPolicy;
    /**
     * Secret bindings for the child sandbox. Resolved per child; never inherited from the snapshot.
     */
    secrets?: Array<SecretBinding>;
};

export type ForkSandboxResponse = {
    sandbox?: Sandbox;
    operation?: Operation;
};

export type GetAnnotationSchemaResponse = {
    /**
     * The requested config version.
     */
    schema?: AnnotationSchema;
};

export type GetArtifactResponse = {
    artifact?: Artifact;
    bytes?: string;
};

export type GetExecutionResponse = {
    execution?: Execution;
};

export type GetForkResponse = {
    fork?: Fork;
};

export type GetOperationResponse = {
    operation?: Operation;
};

export type GetProjectResponse = {
    /**
     * The requested project.
     */
    project?: Project;
};

export type GetRunResponse = {
    /**
     * The requested run, including its live-fork-count roll-up.
     */
    run?: Run;
};

export type GetSandboxResponse = {
    sandbox?: Sandbox;
};

export type GetSnapshotResponse = {
    snapshot?: Snapshot;
};

export type GetUsageSeriesResponse = {
    /**
     * The ordered, contiguous time buckets covering the requested window.
     */
    points?: Array<UsageSeriesPoint>;
};

export type GetUsageSnapshotResponse = {
    /**
     * The point-in-time usage snapshot for the caller's tenant.
     */
    snapshot?: UsageSnapshot;
};

/**
 * The caller's identity, as resolved from their credential by the API edge. The API trusts this
 * resolved identity; it does not re-authenticate.
 */
export type Identity = {
    /**
     * x-hiloop-org-id — the organization the caller acts in.
     */
    orgId?: string;
    /**
     * x-hiloop-tenant-id — the tenant the caller acts in (drives app.tenant_id / RLS downstream).
     */
    tenantId?: string;
    /**
     * x-hiloop-user-id — the user, when the credential is user-scoped; empty for service keys.
     */
    userId?: string;
    /**
     * x-hiloop-auth-method — how the caller authenticated (e.g. "api_key", "session").
     */
    authMethod?: string;
    /**
     * x-hiloop-scope — the granted scope, when present.
     */
    scope?: string;
};

/**
 * Signal a running execution.
 */
export type KillExecutionRequest = {
    executionId?: string;
    /**
     * Signal to deliver. TERMINATE is used when unspecified.
     */
    signal?: 'EXEC_SIGNAL_UNSPECIFIED' | 'EXEC_SIGNAL_INTERRUPT' | 'EXEC_SIGNAL_TERMINATE' | 'EXEC_SIGNAL_KILL' | 'EXEC_SIGNAL_EOF';
};

export type KillExecutionResponse = {
    [key: string]: unknown;
};

export type ListAnnotationSchemasResponse = {
    /**
     * The configs in the caller's tenant. By default the latest live version per name; with
     * include_archived, every version, newest first.
     */
    schemas?: Array<AnnotationSchema>;
};

export type ListDataViewsResponse = {
    /**
     * The tenant's structured data views (own + un-overridden builtins).
     */
    views?: Array<DataView>;
};

export type ListForkNodesResponse = {
    /**
     * The fork tree, ordered by fork path (breadth-first within each level).
     */
    forkNodes?: Array<ForkNode>;
};

export type ListProjectsResponse = {
    /**
     * The projects on this page, newest first.
     */
    projects?: Array<Project>;
    /**
     * The token to pass as page_token to fetch the next page. Empty when there are no more results.
     */
    nextPageToken?: string;
};

export type ListRunsResponse = {
    /**
     * The runs on this page, newest first.
     */
    runs?: Array<Run>;
    /**
     * The token to pass as page_token to fetch the next page. Empty when there are no more results.
     */
    nextPageToken?: string;
};

export type ListRuntimeCapabilitiesResponse = {
    capabilities?: Array<Capability>;
};

export type ListSandboxSecretsResponse = {
    /**
     * The secrets on this page, newest first — metadata only, never the value.
     */
    secrets?: Array<SandboxSecret>;
    /**
     * The token to pass as page_token to fetch the next page. Empty when there are no more results.
     */
    nextPageToken?: string;
};

export type ListSandboxesResponse = {
    /**
     * The sandboxes on this page, newest first.
     */
    sandboxes?: Array<Sandbox>;
    /**
     * The token to pass as page_token to fetch the next page. Empty when there are no more results.
     */
    nextPageToken?: string;
};

export type ListSavedViewsResponse = {
    /**
     * The tenant's saved views, in a stable order (by name).
     */
    views?: Array<SavedView>;
};

export type ListSnapshotsResponse = {
    snapshots?: Array<Snapshot>;
};

export type OciImage = {
    reference?: string;
    digest?: string;
};

export type Operation = {
    id?: string;
    tenantId?: string;
    resourceType?: string;
    resourceId?: string;
    kind?: string;
    state?: string;
    resultJson?: string;
    errorJson?: string;
};

/**
 * A project record (the subset the API returns).
 */
export type Project = {
    /**
     * The project id.
     */
    id?: string;
    /**
     * The tenant the project belongs to (derived from the caller's scope, echoed for convenience).
     */
    tenantId?: string;
    /**
     * The project slug — unique within the tenant.
     */
    slug?: string;
    /**
     * The human-readable project name.
     */
    name?: string;
    /**
     * When the project was created (RFC 3339).
     */
    createdAt?: string;
    /**
     * Optimistic-concurrency version, bumped on every update. Echo it back as the `If-Match` request header to make a later update conditional — if the project changed meanwhile the server rejects the update with error code `precondition_failed` instead of overwriting.
     */
    version?: string;
};

/**
 * Opaque image reference interpreted by the selected runtime adapter.
 */
export type ProviderNativeImage = {
    reference?: string;
};

/**
 * Create or replace a data view by name (upsert). The path `{name}` is authoritative; a `name` inside
 * the body is ignored.
 */
export type PutDataViewRequest = {
    /**
     * The view name (per-tenant unique); supplied by the path.
     */
    name?: string;
    /**
     * An optional human description.
     */
    description?: string;
    /**
     * The structured spec (opaque JSON, the engine's tagged `DataViewSpec`). Compile-validated before
     * store.
     */
    spec?: {
        [key: string]: unknown;
    };
};

/**
 * Create or replace a saved view by name (upsert). The path `{name}` is authoritative.
 */
export type PutSavedViewRequest = {
    /**
     * The view name (per-tenant unique); supplied by the path.
     */
    name?: string;
    /**
     * The view's `SELECT` SQL.
     */
    sql?: string;
};

export type QueryResponse = {
    rows?: Array<Row>;
};

export type RegisterAnnotationSchemaRequest = {
    /**
     * The schema name — unique per tenant across versions. A new registration of an existing name
     * creates the next version; an unseen name starts at version 1.
     */
    name?: string;
    /**
     * The JSON Schema document (draft 2020-12) as a JSON string. Must be a JSON object.
     */
    jsonSchema?: string;
    /**
     * An optional human-readable description for this version.
     */
    description?: string;
};

export type RegisterAnnotationSchemaResponse = {
    /**
     * The registered config version.
     */
    schema?: AnnotationSchema;
};

/**
 * Reserved resources summed over the active runtime instance of each in-use sandbox. These are the
 * requested ("reserved") amounts the sandboxes asked for, not measured live utilization.
 */
export type ReservedResources = {
    /**
     * Total reserved virtual CPUs.
     */
    cpus?: string;
    /**
     * Total reserved memory in MiB.
     */
    memoryMb?: string;
    /**
     * Total reserved root disk in MiB.
     */
    diskMb?: string;
    /**
     * Total reserved accelerators (e.g. GPUs). Best-effort: counted only for sandboxes whose spec
     * requested an accelerator, so a tenant running no accelerator workloads reports zero.
     */
    gpus?: string;
};

export type ResolveSandboxSecretRequest = {
    /**
     * The name of the secret to resolve, in the caller's tenant.
     */
    name?: string;
};

export type ResolveSandboxSecretResponse = {
    /**
     * The decrypted secret value. Returned only to the in-sandbox proxy over the authenticated, TLS
     * channel so it can inject it into the matching outbound request.
     */
    value?: string;
};

export type ResourceSpec = {
    cpus?: number;
    memoryMb?: string;
    diskMb?: string;
    architecture?: 'ARCHITECTURE_UNSPECIFIED' | 'ARCHITECTURE_X86_64' | 'ARCHITECTURE_AARCH64';
};

export type RestoreSnapshotRequest = {
    snapshotId?: string;
    projectId?: string;
    name?: string;
    image?: SandboxImage;
    resources?: ResourceSpec;
    requestedCapabilities?: Array<CapabilityRequirement>;
    labels?: {
        [key: string]: string;
    };
    contents?: string;
    allowFallback?: boolean;
    /**
     * Activity-capture policy for the restored sandbox. Enabled by default; set
     * policy=CAPTURE_POLICY_DISABLED to restore onto an image without the capture toolchain.
     */
    capture?: CaptureSpec;
    /**
     * Outbound network policy for the restored sandbox. Omitted leaves egress unbounded.
     */
    egress?: EgressPolicy;
    /**
     * Secret bindings for the restored sandbox. Resolved per child; never inherited from the snapshot.
     */
    secrets?: Array<SecretBinding>;
};

export type RestoreSnapshotResponse = {
    sandbox?: Sandbox;
    operation?: Operation;
};

export type RevokeSandboxSecretResponse = {
    /**
     * The revoked secret's metadata (with revoked_at set).
     */
    secret?: SandboxSecret;
};

export type RollupRequest = {
    spec?: RollupSpec;
};

/**
 * One rollup bucket per row: the `gen_ai_model` and `time_bucket` grouping columns plus the aggregate
 * metrics (count, sum_prompt_tokens, sum_completion_tokens, sum_cost_usd, avg_cost_usd, p95_cost_usd,
 * p50_ts_wall_ns, p95_ts_wall_ns).
 */
export type RollupResponse = {
    rows?: Array<Row>;
};

/**
 * A Q4 rollup: columnar aggregation over the promoted token/cost/latency/status columns, grouped by
 * gen_ai_model and a fixed-width wall-clock time bucket. Scoped to a single run when `run_id` is set,
 * or across every run for the tenant when it is empty. Restricted to the `llm` signal so non-llm
 * events never form a NULL-model group. The tenant is taken from request identity, never from this
 * body.
 */
export type RollupSpec = {
    /**
     * The run (session) to roll up. Optional: present scopes the rollup to that run; absent (empty)
     * rolls up across every run for the tenant. The forced tenant predicate is AND-ed in either way.
     */
    runId?: string;
    /**
     * Time-bucket width in nanoseconds; each event is grouped into `ts_wall_ns / bucket_ns`. Required
     * and must be > 0.
     */
    bucketNs?: string;
    /**
     * Optional exact gen_ai_model to restrict to (e.g. "gpt-4"); empty means all models.
     */
    modelFilter?: string;
    /**
     * Optional minimum http_status_code (inclusive) to restrict to — the error-rate lever
     * (e.g. 400 keeps only >= 400). 0 means no status floor.
     */
    statusMin?: string;
};

export type RotateSandboxSecretRequest = {
    /**
     * The secret id to rotate.
     */
    id?: string;
    /**
     * The new secret value. WRITE-ONLY: stored encrypted as a new version and never returned.
     */
    value?: string;
};

export type RotateSandboxSecretResponse = {
    /**
     * The rotated secret's metadata (with the new current_version and rotated_at set).
     */
    secret?: SandboxSecret;
};

/**
 * One result row: column name -> typed value. For aggregate surfaces (rollup) the columns are the
 * grouping columns plus one per aggregate metric (e.g. "p95_cost_usd"). Reused by the view service.
 */
export type Row = {
    columns?: {
        [key: string]: AttributeValue;
    };
};

/**
 * A run record (the subset the API returns). Intentionally carries no cost or spend roll-up: the
 * product is generic and does not surface cost by default.
 */
export type Run = {
    /**
     * The run id (a client-supplied ULID, shared with telemetry).
     */
    id?: string;
    /**
     * The tenant the run belongs to (derived from the caller's scope, echoed for convenience).
     */
    tenantId?: string;
    /**
     * The project the run belongs to.
     */
    projectId?: string;
    /**
     * An optional human-readable label.
     */
    label?: string;
    /**
     * The run lifecycle status: pending, running, succeeded, failed, or canceled.
     */
    status?: string;
    /**
     * The user that created the run, when recorded (empty otherwise).
     */
    createdBy?: string;
    /**
     * When the run started executing (RFC 3339), empty if it has not started.
     */
    startedAt?: string;
    /**
     * When the run finished (RFC 3339), empty if it is still in flight.
     */
    endedAt?: string;
    /**
     * When the run record was created (RFC 3339).
     */
    createdAt?: string;
    /**
     * The number of active (non-archived) fork nodes in the run's fork tree.
     */
    liveForkCount?: string;
};

export type Sandbox = {
    id?: string;
    tenantId?: string;
    projectId?: string;
    name?: string;
    desiredState?: string;
    observedState?: string;
    activeGeneration?: string;
    version?: string;
    /**
     * Fork-tree node that represents this sandbox as a fork source. Present for project-backed
     * sandboxes; absent project-less sandboxes are not fork sources.
     */
    forkNodeId?: string;
};

export type SandboxImage = {
    oci?: OciImage;
    buildArtifact?: BuildArtifactImage;
    providerNative?: ProviderNativeImage;
};

/**
 * A sandbox-secret record — metadata only, never the value.
 */
export type SandboxSecret = {
    /**
     * The secret id.
     */
    id?: string;
    /**
     * The human-readable secret name — unique within the tenant. The sandbox spec references it by name.
     */
    name?: string;
    /**
     * The credential kind.
     */
    kind?: 'SECRET_KIND_UNSPECIFIED' | 'SECRET_KIND_API_KEY' | 'SECRET_KIND_BEARER' | 'SECRET_KIND_BASIC' | 'SECRET_KIND_CUSTOM';
    /**
     * The outbound host the value is injected into, when bound to one (empty for an unbound secret).
     */
    destHost?: string;
    /**
     * The header the value is injected as, when applicable (empty when the kind implies it).
     */
    destHeader?: string;
    /**
     * The auth scheme prefix (e.g. `Bearer`), when applicable.
     */
    scheme?: string;
    /**
     * The current version number. Incremented on each rotation; 0 before the first value is set.
     */
    currentVersion?: string;
    /**
     * When the secret was created (RFC 3339).
     */
    createdAt?: string;
    /**
     * When the secret was last rotated, if ever (RFC 3339).
     */
    rotatedAt?: string;
    /**
     * When the secret expires, if an expiry is set (RFC 3339).
     */
    expiresAt?: string;
    /**
     * When the secret was revoked, if it has been (RFC 3339). A revoked secret resolves to nothing.
     */
    revokedAt?: string;
};

/**
 * The count of active sandboxes in one observed lifecycle state.
 */
export type SandboxStateCount = {
    /**
     * The sandbox observed state (e.g. running, ready, paused, provisioning).
     */
    observedState?: string;
    /**
     * How many non-deleted sandboxes are in this state.
     */
    count?: string;
};

/**
 * A saved SQL view: a named, per-tenant `SELECT` re-validated on every run.
 */
export type SavedView = {
    /**
     * The view name, unique within a tenant.
     */
    name?: string;
    /**
     * The stored `SELECT` SQL. Validated before store and re-validated on every execution.
     */
    sql?: string;
};

/**
 * Binds a stored sandbox secret to a placeholder the agent sees and the outbound target the value is
 * injected into. The agent only ever observes the placeholder; the real value is injected in flight
 * and never written into the sandbox environment, disk, snapshot, or captured telemetry.
 */
export type SecretBinding = {
    /**
     * Name of the stored sandbox secret to resolve.
     */
    name?: string;
    /**
     * Placeholder environment variable the agent sees in place of the value.
     */
    env?: string;
    /**
     * Outbound target the resolved value is injected into (e.g. a host or header).
     */
    bind?: string;
};

/**
 * Deliver more input to a running execution: either standard input bytes or a control signal.
 */
export type SendExecutionInputRequest = {
    executionId?: string;
    /**
     * Bytes appended to the process's standard input.
     */
    stdin?: string;
    /**
     * A control signal delivered to the process.
     */
    signal?: 'EXEC_SIGNAL_UNSPECIFIED' | 'EXEC_SIGNAL_INTERRUPT' | 'EXEC_SIGNAL_TERMINATE' | 'EXEC_SIGNAL_KILL' | 'EXEC_SIGNAL_EOF';
};

export type SendExecutionInputResponse = {
    [key: string]: unknown;
};

export type Snapshot = {
    id?: string;
    tenantId?: string;
    projectId?: string;
    sourceSandboxId?: string;
    status?: string;
    requestedSemanticsJson?: string;
    effectiveSemanticsJson?: string;
    sizeBytes?: string;
    legalHold?: boolean;
};

/**
 * Start an interactive command execution that can be streamed and driven over time.
 */
export type StartExecutionRequest = {
    sandboxId?: string;
    command?: CommandSpec;
    /**
     * Optional bytes written to the process's standard input at start.
     */
    stdin?: string;
    /**
     * Allocate a pseudo-terminal for the execution.
     */
    pty?: boolean;
};

export type StartExecutionResponse = {
    /**
     * The durable execution row for the process the in-sandbox control agent spawned. Stream its output
     * with StreamExecution, drive it with SendExecutionInput, and stop it with KillExecution.
     */
    execution?: Execution;
};

export type UpdateProjectRequest = {
    /**
     * The project id to update.
     */
    id?: string;
    /**
     * The new human-readable name. The slug is immutable.
     */
    name?: string;
};

export type UpdateProjectResponse = {
    /**
     * The updated project.
     */
    project?: Project;
};

/**
 * One time bucket of a tenant's reserved-resource usage, for the usage-over-time charts. Reserved
 * amounts are the time-weighted average over the bucket (rounded).
 */
export type UsageSeriesPoint = {
    /**
     * Bucket start (RFC 3339, UTC). Buckets are contiguous and `bucket_seconds` wide.
     */
    bucketStart?: string;
    /**
     * Time-weighted average reserved virtual CPUs during the bucket.
     */
    reservedCpus?: string;
    /**
     * Time-weighted average reserved memory (MiB) during the bucket.
     */
    reservedMemoryMb?: string;
    /**
     * Time-weighted average reserved accelerators during the bucket.
     */
    reservedGpus?: string;
};

/**
 * A point-in-time, tenant-scoped usage snapshot.
 */
export type UsageSnapshot = {
    /**
     * The tenant the snapshot covers (derived from the caller's scope, echoed for convenience).
     */
    tenantId?: string;
    /**
     * The number of active (non-deleted, non-terminal) sandboxes.
     */
    activeSandboxCount?: string;
    /**
     * The per-observed-state breakdown of non-deleted sandboxes, including terminal states, so the
     * caller can render the full distribution. Ordered by observed state.
     */
    sandboxStateCounts?: Array<SandboxStateCount>;
    /**
     * Resources reserved by the tenant's in-use sandboxes right now.
     */
    reserved?: ReservedResources;
    /**
     * The tenant's configured resource quota — the denominator for utilization. A configured display
     * quota (a plan limit), not measured provider capacity; managed providers expose no fleet total.
     */
    capacity?: ReservedResources;
    /**
     * Resources held by idle (paused) sandboxes that could be reclaimed by stopping them. A subset of
     * `reserved`. `disk_mb` is not tracked here.
     */
    reclaimable?: ReservedResources;
};

export type WhoAmIResponse = {
    /**
     * The caller identity reflected from the request's x-hiloop-* headers.
     */
    identity?: Identity;
};

export type AnnotationSchemaServiceListAnnotationSchemasData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * When true, return every version (live and archived) for the tenant; otherwise return only the
         * latest live version per name.
         */
        includeArchived?: boolean;
    };
    url: '/v1/annotation-schemas';
};

export type AnnotationSchemaServiceListAnnotationSchemasResponses = {
    /**
     * OK
     */
    200: ListAnnotationSchemasResponse;
};

export type AnnotationSchemaServiceListAnnotationSchemasResponse = AnnotationSchemaServiceListAnnotationSchemasResponses[keyof AnnotationSchemaServiceListAnnotationSchemasResponses];

export type AnnotationSchemaServiceRegisterAnnotationSchemaData = {
    body: RegisterAnnotationSchemaRequest;
    path?: never;
    query?: never;
    url: '/v1/annotation-schemas';
};

export type AnnotationSchemaServiceRegisterAnnotationSchemaResponses = {
    /**
     * OK
     */
    200: RegisterAnnotationSchemaResponse;
};

export type AnnotationSchemaServiceRegisterAnnotationSchemaResponse = AnnotationSchemaServiceRegisterAnnotationSchemaResponses[keyof AnnotationSchemaServiceRegisterAnnotationSchemaResponses];

export type AnnotationSchemaServiceGetAnnotationSchemaData = {
    body?: never;
    path: {
        /**
         * The schema name to fetch.
         */
        name: string;
    };
    query?: {
        /**
         * The specific version to fetch. 0 (or omitted) means the latest live version.
         */
        version?: string;
    };
    url: '/v1/annotation-schemas/{name}';
};

export type AnnotationSchemaServiceGetAnnotationSchemaResponses = {
    /**
     * OK
     */
    200: GetAnnotationSchemaResponse;
};

export type AnnotationSchemaServiceGetAnnotationSchemaResponse = AnnotationSchemaServiceGetAnnotationSchemaResponses[keyof AnnotationSchemaServiceGetAnnotationSchemaResponses];

export type AnnotationSchemaServiceArchiveAnnotationSchemaData = {
    body: ArchiveAnnotationSchemaRequest;
    path: {
        /**
         * The schema name to archive.
         */
        name: string;
    };
    query?: never;
    url: '/v1/annotation-schemas/{name}:archive';
};

export type AnnotationSchemaServiceArchiveAnnotationSchemaResponses = {
    /**
     * OK
     */
    200: ArchiveAnnotationSchemaResponse;
};

export type AnnotationSchemaServiceArchiveAnnotationSchemaResponse = AnnotationSchemaServiceArchiveAnnotationSchemaResponses[keyof AnnotationSchemaServiceArchiveAnnotationSchemaResponses];

export type RuntimeServiceGetArtifactData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/artifacts/{id}';
};

export type RuntimeServiceGetArtifactResponses = {
    /**
     * OK
     */
    200: GetArtifactResponse;
};

export type RuntimeServiceGetArtifactResponse = RuntimeServiceGetArtifactResponses[keyof RuntimeServiceGetArtifactResponses];

export type RuntimeServiceSendExecutionInputData = {
    body: SendExecutionInputRequest;
    path: {
        executionId: string;
    };
    query?: never;
    url: '/v1/executions/{executionId}:input';
};

export type RuntimeServiceSendExecutionInputResponses = {
    /**
     * OK
     */
    200: SendExecutionInputResponse;
};

export type RuntimeServiceSendExecutionInputResponse = RuntimeServiceSendExecutionInputResponses[keyof RuntimeServiceSendExecutionInputResponses];

export type RuntimeServiceKillExecutionData = {
    body: KillExecutionRequest;
    path: {
        executionId: string;
    };
    query?: never;
    url: '/v1/executions/{executionId}:kill';
};

export type RuntimeServiceKillExecutionResponses = {
    /**
     * OK
     */
    200: KillExecutionResponse;
};

export type RuntimeServiceKillExecutionResponse = RuntimeServiceKillExecutionResponses[keyof RuntimeServiceKillExecutionResponses];

export type RuntimeServiceStreamExecutionData = {
    body?: never;
    path: {
        executionId: string;
    };
    query?: never;
    url: '/v1/executions/{executionId}:stream';
};

export type RuntimeServiceStreamExecutionResponses = {
    /**
     * OK
     */
    200: ExecOutputEvent;
};

export type RuntimeServiceStreamExecutionResponse = RuntimeServiceStreamExecutionResponses[keyof RuntimeServiceStreamExecutionResponses];

export type RuntimeServiceGetExecutionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/executions/{id}';
};

export type RuntimeServiceGetExecutionResponses = {
    /**
     * OK
     */
    200: GetExecutionResponse;
};

export type RuntimeServiceGetExecutionResponse = RuntimeServiceGetExecutionResponses[keyof RuntimeServiceGetExecutionResponses];

export type RuntimeServiceGetForkData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/forks/{id}';
};

export type RuntimeServiceGetForkResponses = {
    /**
     * OK
     */
    200: GetForkResponse;
};

export type RuntimeServiceGetForkResponse = RuntimeServiceGetForkResponses[keyof RuntimeServiceGetForkResponses];

export type RuntimeServiceGetOperationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/operations/{id}';
};

export type RuntimeServiceGetOperationResponses = {
    /**
     * OK
     */
    200: GetOperationResponse;
};

export type RuntimeServiceGetOperationResponse = RuntimeServiceGetOperationResponses[keyof RuntimeServiceGetOperationResponses];

export type ProjectServiceListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The maximum number of projects to return. The server caps and defaults this; 0 means "use the
         * server default".
         */
        pageSize?: number;
        /**
         * An opaque page token from a previous response's next_page_token. Empty for the first page.
         */
        pageToken?: string;
    };
    url: '/v1/projects';
};

export type ProjectServiceListProjectsResponses = {
    /**
     * OK
     */
    200: ListProjectsResponse;
};

export type ProjectServiceListProjectsResponse = ProjectServiceListProjectsResponses[keyof ProjectServiceListProjectsResponses];

export type ProjectServiceCreateProjectData = {
    body: CreateProjectRequest;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type ProjectServiceCreateProjectResponses = {
    /**
     * OK
     */
    200: CreateProjectResponse;
};

export type ProjectServiceCreateProjectResponse = ProjectServiceCreateProjectResponses[keyof ProjectServiceCreateProjectResponses];

export type ProjectServiceGetProjectData = {
    body?: never;
    path: {
        /**
         * The project id to fetch.
         */
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type ProjectServiceGetProjectResponses = {
    /**
     * OK
     */
    200: GetProjectResponse;
};

export type ProjectServiceGetProjectResponse = ProjectServiceGetProjectResponses[keyof ProjectServiceGetProjectResponses];

export type ProjectServiceUpdateProjectData = {
    body: UpdateProjectRequest;
    path: {
        /**
         * The project id to update.
         */
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type ProjectServiceUpdateProjectResponses = {
    /**
     * OK
     */
    200: UpdateProjectResponse;
};

export type ProjectServiceUpdateProjectResponse = ProjectServiceUpdateProjectResponses[keyof ProjectServiceUpdateProjectResponses];

export type RunServiceListRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The maximum number of runs to return. The server caps and defaults this; 0 means "use the server
         * default".
         */
        pageSize?: number;
        /**
         * An opaque page token from a previous response's next_page_token. Empty for the first page.
         */
        pageToken?: string;
        /**
         * Optional run status filter (pending, running, succeeded, failed, canceled). Empty returns all.
         */
        status?: string;
        /**
         * Optional creator filter (an app user id). Empty returns runs from any creator.
         */
        createdBy?: string;
        /**
         * Optional lower bound on created_at (RFC 3339, inclusive). Empty applies no lower bound.
         */
        createdAfter?: string;
        /**
         * Optional upper bound on created_at (RFC 3339, exclusive). Empty applies no upper bound.
         */
        createdBefore?: string;
    };
    url: '/v1/runs';
};

export type RunServiceListRunsResponses = {
    /**
     * OK
     */
    200: ListRunsResponse;
};

export type RunServiceListRunsResponse = RunServiceListRunsResponses[keyof RunServiceListRunsResponses];

export type RunServiceGetRunData = {
    body?: never;
    path: {
        /**
         * The run id to fetch.
         */
        id: string;
    };
    query?: never;
    url: '/v1/runs/{id}';
};

export type RunServiceGetRunResponses = {
    /**
     * OK
     */
    200: GetRunResponse;
};

export type RunServiceGetRunResponse = RunServiceGetRunResponses[keyof RunServiceGetRunResponses];

export type RunServiceListForkNodesData = {
    body?: never;
    path: {
        /**
         * The run whose fork tree to list.
         */
        runId: string;
    };
    query?: never;
    url: '/v1/runs/{runId}/fork-nodes';
};

export type RunServiceListForkNodesResponses = {
    /**
     * OK
     */
    200: ListForkNodesResponse;
};

export type RunServiceListForkNodesResponse = RunServiceListForkNodesResponses[keyof RunServiceListForkNodesResponses];

export type RuntimeServiceListRuntimeCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/runtime/capabilities';
};

export type RuntimeServiceListRuntimeCapabilitiesResponses = {
    /**
     * OK
     */
    200: ListRuntimeCapabilitiesResponse;
};

export type RuntimeServiceListRuntimeCapabilitiesResponse = RuntimeServiceListRuntimeCapabilitiesResponses[keyof RuntimeServiceListRuntimeCapabilitiesResponses];

export type RuntimeServiceListSandboxesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The maximum number of sandboxes to return. The server caps and defaults this; 0 means "use the
         * server default".
         */
        pageSize?: number;
        /**
         * An opaque page token from a previous response's next_page_token. Empty for the first page.
         */
        pageToken?: string;
        /**
         * Optional project filter. Empty returns sandboxes across all of the caller's projects.
         */
        projectId?: string;
        /**
         * Optional observed-state filter (e.g. running, paused, stopped). Empty returns all states.
         */
        observedState?: string;
    };
    url: '/v1/sandboxes';
};

export type RuntimeServiceListSandboxesResponses = {
    /**
     * OK
     */
    200: ListSandboxesResponse;
};

export type RuntimeServiceListSandboxesResponse = RuntimeServiceListSandboxesResponses[keyof RuntimeServiceListSandboxesResponses];

export type RuntimeServiceCreateSandboxData = {
    body: CreateSandboxRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/sandboxes';
};

export type RuntimeServiceCreateSandboxResponses = {
    /**
     * OK
     */
    200: CreateSandboxResponse;
};

export type RuntimeServiceCreateSandboxResponse = RuntimeServiceCreateSandboxResponses[keyof RuntimeServiceCreateSandboxResponses];

export type RuntimeServiceDeleteSandboxData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}';
};

export type RuntimeServiceDeleteSandboxResponses = {
    /**
     * OK
     */
    200: DeleteSandboxResponse;
};

export type RuntimeServiceDeleteSandboxResponse = RuntimeServiceDeleteSandboxResponses[keyof RuntimeServiceDeleteSandboxResponses];

export type RuntimeServiceGetSandboxData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}';
};

export type RuntimeServiceGetSandboxResponses = {
    /**
     * OK
     */
    200: GetSandboxResponse;
};

export type RuntimeServiceGetSandboxResponse = RuntimeServiceGetSandboxResponses[keyof RuntimeServiceGetSandboxResponses];

export type RuntimeServiceStartExecutionData = {
    body: StartExecutionRequest;
    path: {
        sandboxId: string;
    };
    query?: never;
    url: '/v1/sandboxes/{sandboxId}/executions';
};

export type RuntimeServiceStartExecutionResponses = {
    /**
     * OK
     */
    200: StartExecutionResponse;
};

export type RuntimeServiceStartExecutionResponse = RuntimeServiceStartExecutionResponses[keyof RuntimeServiceStartExecutionResponses];

export type RuntimeServiceFileFromArtifactData = {
    body: FileFromArtifactRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path: {
        sandboxId: string;
    };
    query?: never;
    url: '/v1/sandboxes/{sandboxId}/files:from-artifact';
};

export type RuntimeServiceFileFromArtifactResponses = {
    /**
     * OK
     */
    200: FileFromArtifactResponse;
};

export type RuntimeServiceFileFromArtifactResponse = RuntimeServiceFileFromArtifactResponses[keyof RuntimeServiceFileFromArtifactResponses];

export type RuntimeServiceFileToArtifactData = {
    body: FileToArtifactRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path: {
        sandboxId: string;
    };
    query?: never;
    url: '/v1/sandboxes/{sandboxId}/files:to-artifact';
};

export type RuntimeServiceFileToArtifactResponses = {
    /**
     * OK
     */
    200: FileToArtifactResponse;
};

export type RuntimeServiceFileToArtifactResponse = RuntimeServiceFileToArtifactResponses[keyof RuntimeServiceFileToArtifactResponses];

export type RuntimeServiceCreateSnapshotData = {
    body: CreateSnapshotRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path: {
        sandboxId: string;
    };
    query?: never;
    url: '/v1/sandboxes/{sandboxId}/snapshots';
};

export type RuntimeServiceCreateSnapshotResponses = {
    /**
     * OK
     */
    200: CreateSnapshotResponse;
};

export type RuntimeServiceCreateSnapshotResponse = RuntimeServiceCreateSnapshotResponses[keyof RuntimeServiceCreateSnapshotResponses];

export type RuntimeServiceExecuteSandboxData = {
    body: ExecuteSandboxRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path: {
        sandboxId: string;
    };
    query?: never;
    url: '/v1/sandboxes/{sandboxId}:execute';
};

export type RuntimeServiceExecuteSandboxResponses = {
    /**
     * OK
     */
    200: ExecuteSandboxResponse;
};

export type RuntimeServiceExecuteSandboxResponse = RuntimeServiceExecuteSandboxResponses[keyof RuntimeServiceExecuteSandboxResponses];

export type RuntimeServiceForkSandboxData = {
    body: ForkSandboxRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path: {
        sourceSandboxId: string;
    };
    query?: never;
    url: '/v1/sandboxes/{sourceSandboxId}:fork';
};

export type RuntimeServiceForkSandboxResponses = {
    /**
     * OK
     */
    200: ForkSandboxResponse;
};

export type RuntimeServiceForkSandboxResponse = RuntimeServiceForkSandboxResponses[keyof RuntimeServiceForkSandboxResponses];

export type SecretServiceListSandboxSecretsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The maximum number of secrets to return. The server caps and defaults this; 0 means "use the
         * server default".
         */
        pageSize?: number;
        /**
         * An opaque page token from a previous response's next_page_token. Empty for the first page.
         */
        pageToken?: string;
    };
    url: '/v1/secrets';
};

export type SecretServiceListSandboxSecretsResponses = {
    /**
     * OK
     */
    200: ListSandboxSecretsResponse;
};

export type SecretServiceListSandboxSecretsResponse = SecretServiceListSandboxSecretsResponses[keyof SecretServiceListSandboxSecretsResponses];

export type SecretServiceCreateSandboxSecretData = {
    body: CreateSandboxSecretRequest;
    path?: never;
    query?: never;
    url: '/v1/secrets';
};

export type SecretServiceCreateSandboxSecretResponses = {
    /**
     * OK
     */
    200: CreateSandboxSecretResponse;
};

export type SecretServiceCreateSandboxSecretResponse = SecretServiceCreateSandboxSecretResponses[keyof SecretServiceCreateSandboxSecretResponses];

export type SecretServiceResolveSandboxSecretData = {
    body: ResolveSandboxSecretRequest;
    path?: never;
    query?: never;
    url: '/v1/secrets/resolve';
};

export type SecretServiceResolveSandboxSecretResponses = {
    /**
     * OK
     */
    200: ResolveSandboxSecretResponse;
};

export type SecretServiceResolveSandboxSecretResponse = SecretServiceResolveSandboxSecretResponses[keyof SecretServiceResolveSandboxSecretResponses];

export type SecretServiceRevokeSandboxSecretData = {
    body?: never;
    path: {
        /**
         * The secret id to revoke.
         */
        id: string;
    };
    query?: never;
    url: '/v1/secrets/{id}';
};

export type SecretServiceRevokeSandboxSecretResponses = {
    /**
     * OK
     */
    200: RevokeSandboxSecretResponse;
};

export type SecretServiceRevokeSandboxSecretResponse = SecretServiceRevokeSandboxSecretResponses[keyof SecretServiceRevokeSandboxSecretResponses];

export type SecretServiceRotateSandboxSecretData = {
    body: RotateSandboxSecretRequest;
    path: {
        /**
         * The secret id to rotate.
         */
        id: string;
    };
    query?: never;
    url: '/v1/secrets/{id}/rotate';
};

export type SecretServiceRotateSandboxSecretResponses = {
    /**
     * OK
     */
    200: RotateSandboxSecretResponse;
};

export type SecretServiceRotateSandboxSecretResponse = SecretServiceRotateSandboxSecretResponses[keyof SecretServiceRotateSandboxSecretResponses];

export type RuntimeServiceListSnapshotsData = {
    body?: never;
    path?: never;
    query: {
        projectId: string;
    };
    url: '/v1/snapshots';
};

export type RuntimeServiceListSnapshotsResponses = {
    /**
     * OK
     */
    200: ListSnapshotsResponse;
};

export type RuntimeServiceListSnapshotsResponse = RuntimeServiceListSnapshotsResponses[keyof RuntimeServiceListSnapshotsResponses];

export type RuntimeServiceDeleteSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/snapshots/{id}';
};

export type RuntimeServiceDeleteSnapshotResponses = {
    /**
     * OK
     */
    200: DeleteSnapshotResponse;
};

export type RuntimeServiceDeleteSnapshotResponse = RuntimeServiceDeleteSnapshotResponses[keyof RuntimeServiceDeleteSnapshotResponses];

export type RuntimeServiceGetSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/snapshots/{id}';
};

export type RuntimeServiceGetSnapshotResponses = {
    /**
     * OK
     */
    200: GetSnapshotResponse;
};

export type RuntimeServiceGetSnapshotResponse = RuntimeServiceGetSnapshotResponses[keyof RuntimeServiceGetSnapshotResponses];

export type RuntimeServiceRestoreSnapshotData = {
    body: RestoreSnapshotRequest;
    headers?: {
        /**
         * Optional idempotency key for this mutation. Supply one (the official SDKs generate it for you) to make a retry safe — repeating the request with the same key returns the original result instead of performing the action twice. Omit it and each call is treated as a new request.
         */
        'idempotency-key'?: string;
    };
    path: {
        snapshotId: string;
    };
    query?: never;
    url: '/v1/snapshots/{snapshotId}:restore';
};

export type RuntimeServiceRestoreSnapshotResponses = {
    /**
     * OK
     */
    200: RestoreSnapshotResponse;
};

export type RuntimeServiceRestoreSnapshotResponse = RuntimeServiceRestoreSnapshotResponses[keyof RuntimeServiceRestoreSnapshotResponses];

export type AnnotationServiceAnnotateData = {
    body: AnnotateRequest;
    path?: never;
    query?: never;
    url: '/v1/telemetry/annotations';
};

export type AnnotationServiceAnnotateResponses = {
    /**
     * OK
     */
    200: AnnotateResponse;
};

export type AnnotationServiceAnnotateResponse = AnnotationServiceAnnotateResponses[keyof AnnotationServiceAnnotateResponses];

export type AnnotationServiceAnnotateRangeData = {
    body: AnnotateRangeRequest;
    path?: never;
    query?: never;
    url: '/v1/telemetry/annotations:range';
};

export type AnnotationServiceAnnotateRangeResponses = {
    /**
     * OK
     */
    200: AnnotateResponse;
};

export type AnnotationServiceAnnotateRangeResponse = AnnotationServiceAnnotateRangeResponses[keyof AnnotationServiceAnnotateRangeResponses];

export type TelemetryQueryServiceBranchDiffData = {
    body: BranchDiffRequest;
    path?: never;
    query?: never;
    url: '/v1/telemetry/branch-diff';
};

export type TelemetryQueryServiceBranchDiffResponses = {
    /**
     * OK
     */
    200: BranchDiffResponse;
};

export type TelemetryQueryServiceBranchDiffResponse = TelemetryQueryServiceBranchDiffResponses[keyof TelemetryQueryServiceBranchDiffResponses];

export type TelemetryViewServiceListDataViewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/telemetry/data-views';
};

export type TelemetryViewServiceListDataViewsResponses = {
    /**
     * OK
     */
    200: ListDataViewsResponse;
};

export type TelemetryViewServiceListDataViewsResponse = TelemetryViewServiceListDataViewsResponses[keyof TelemetryViewServiceListDataViewsResponses];

export type TelemetryViewServiceDeleteDataViewData = {
    body?: never;
    path: {
        /**
         * The data view to delete.
         */
        name: string;
    };
    query?: never;
    url: '/v1/telemetry/data-views/{name}';
};

export type TelemetryViewServiceDeleteDataViewResponses = {
    /**
     * OK
     */
    200: DeleteDataViewResponse;
};

export type TelemetryViewServiceDeleteDataViewResponse = TelemetryViewServiceDeleteDataViewResponses[keyof TelemetryViewServiceDeleteDataViewResponses];

export type TelemetryViewServicePutDataViewData = {
    body: PutDataViewRequest;
    path: {
        /**
         * The view name (per-tenant unique); supplied by the path.
         */
        name: string;
    };
    query?: never;
    url: '/v1/telemetry/data-views/{name}';
};

export type TelemetryViewServicePutDataViewResponses = {
    /**
     * OK
     */
    200: DataView;
};

export type TelemetryViewServicePutDataViewResponse = TelemetryViewServicePutDataViewResponses[keyof TelemetryViewServicePutDataViewResponses];

export type TelemetryViewServiceRunDataViewData = {
    body?: never;
    path: {
        /**
         * The data view to run.
         */
        name: string;
    };
    query?: never;
    url: '/v1/telemetry/data-views/{name}:run';
};

export type TelemetryViewServiceRunDataViewResponses = {
    /**
     * OK
     */
    200: QueryResponse;
};

export type TelemetryViewServiceRunDataViewResponse = TelemetryViewServiceRunDataViewResponses[keyof TelemetryViewServiceRunDataViewResponses];

export type TelemetryQueryServiceRollupData = {
    body: RollupRequest;
    path?: never;
    query?: never;
    url: '/v1/telemetry/rollup';
};

export type TelemetryQueryServiceRollupResponses = {
    /**
     * OK
     */
    200: RollupResponse;
};

export type TelemetryQueryServiceRollupResponse = TelemetryQueryServiceRollupResponses[keyof TelemetryQueryServiceRollupResponses];

export type TelemetryViewServiceListSavedViewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/telemetry/views';
};

export type TelemetryViewServiceListSavedViewsResponses = {
    /**
     * OK
     */
    200: ListSavedViewsResponse;
};

export type TelemetryViewServiceListSavedViewsResponse = TelemetryViewServiceListSavedViewsResponses[keyof TelemetryViewServiceListSavedViewsResponses];

export type TelemetryViewServiceDeleteSavedViewData = {
    body?: never;
    path: {
        /**
         * The saved view to delete.
         */
        name: string;
    };
    query?: never;
    url: '/v1/telemetry/views/{name}';
};

export type TelemetryViewServiceDeleteSavedViewResponses = {
    /**
     * OK
     */
    200: DeleteSavedViewResponse;
};

export type TelemetryViewServiceDeleteSavedViewResponse = TelemetryViewServiceDeleteSavedViewResponses[keyof TelemetryViewServiceDeleteSavedViewResponses];

export type TelemetryViewServicePutSavedViewData = {
    body: PutSavedViewRequest;
    path: {
        /**
         * The view name (per-tenant unique); supplied by the path.
         */
        name: string;
    };
    query?: never;
    url: '/v1/telemetry/views/{name}';
};

export type TelemetryViewServicePutSavedViewResponses = {
    /**
     * OK
     */
    200: SavedView;
};

export type TelemetryViewServicePutSavedViewResponse = TelemetryViewServicePutSavedViewResponses[keyof TelemetryViewServicePutSavedViewResponses];

export type TelemetryViewServiceRunSavedViewData = {
    body?: never;
    path: {
        /**
         * The saved view to run.
         */
        name: string;
    };
    query?: never;
    url: '/v1/telemetry/views/{name}:run';
};

export type TelemetryViewServiceRunSavedViewResponses = {
    /**
     * OK
     */
    200: QueryResponse;
};

export type TelemetryViewServiceRunSavedViewResponse = TelemetryViewServiceRunSavedViewResponses[keyof TelemetryViewServiceRunSavedViewResponses];

export type UsageServiceGetUsageSeriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional project filter. Empty aggregates across all of the caller's projects.
         */
        projectId?: string;
        /**
         * Window start (RFC 3339). Empty defaults to 24 hours before the end.
         */
        startTime?: string;
        /**
         * Window end (RFC 3339). Empty defaults to now.
         */
        endTime?: string;
        /**
         * Bucket width in seconds. 0 defaults to 3600 (one hour); the server clamps to [60, 86400]. At most
         * 5000 buckets are returned; for a window that would exceed that, the server keeps the most recent
         * 5000 buckets (widen the bucket for a longer window).
         */
        bucketSeconds?: string;
    };
    url: '/v1/usage/series';
};

export type UsageServiceGetUsageSeriesResponses = {
    /**
     * OK
     */
    200: GetUsageSeriesResponse;
};

export type UsageServiceGetUsageSeriesResponse = UsageServiceGetUsageSeriesResponses[keyof UsageServiceGetUsageSeriesResponses];

export type UsageServiceGetUsageSnapshotData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional project filter. Empty aggregates across all of the caller's projects.
         */
        projectId?: string;
    };
    url: '/v1/usage/snapshot';
};

export type UsageServiceGetUsageSnapshotResponses = {
    /**
     * OK
     */
    200: GetUsageSnapshotResponse;
};

export type UsageServiceGetUsageSnapshotResponse = UsageServiceGetUsageSnapshotResponses[keyof UsageServiceGetUsageSnapshotResponses];

export type IdentityServiceWhoAmIData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/whoami';
};

export type IdentityServiceWhoAmIResponses = {
    /**
     * OK
     */
    200: WhoAmIResponse;
};

export type IdentityServiceWhoAmIResponse = IdentityServiceWhoAmIResponses[keyof IdentityServiceWhoAmIResponses];
